### ISSUE TITLE
Need some improvements like

### ISSUE THREAD

**Issue by fisforfaheem** [NonSpicyBurrito/hoverlens#6]
Thanks for such an amazing tool.

Kindly keep it updated, make LOGO better.

Also add proper Google Flutter Widgets support.

**Comment by NonSpicyBurrito** [comment]
Thanks.

> make LOGO better

I'm not an artsy person to be able to design something that doesn't suck. If anyone wants to take a shot at it, feel free to.

> add proper Google Flutter Widgets support

The extension simply shows the existing hover information, so if your VS Code has hover information for Flutter widgets, they should work with the extension automatically.

**Comment by fisforfaheem** [comment]
Also tell me will it conflict with official vscode hover stuff

**Comment by NonSpicyBurrito** [comment]
It does not.
